---
# Docker compose file for netprobe
# https://github.com/plaintextpackets/netprobe_lite
name: netprobe

networks:
  netprobe:

services:
  redis:
    restart: always
    container_name: netprobe-redis
    image: "redis:latest"
    volumes:
      - ${CONFIG_PATH}/redis/redis.conf:/etc/redis/redis.conf
    networks:
      - netprobe
    dns:
      - 8.8.8.8
      - 8.8.4.4

  netprobe:
    restart: always
    container_name: netprobe-probe
    image: "plaintextpackets/netprobe:latest"
    pull_policy: always
    environment:
      NP_MODULE: "FULL"
      NP_SITES: "google.com,facebook.com,twitter.com,youtube.com"
      NP_DNS_TEST_SITE: "google.com"

      NP_DNS_NAMESERVER_1: "Google"
      NP_DNS_NAMESERVER_1_IP: "8.8.8.8"
      NP_DNS_NAMESERVER_2: "Quad9"
      NP_DNS_NAMESERVER_2_IP: "9.9.9.9"
      NP_DNS_NAMESERVER_3: "CloudFlare"
      NP_DNS_NAMESERVER_3_IP: "1.1.1.1"
      NP_DNS_NAMESERVER_4: "OpenDNS"
      NP_DNS_NAMESERVER_4_IP: "208.67.222.222"

      NP_LOCAL_DNS_NAMESERVER_1: "Local DNS"
      NP_LOCAL_DNS_NAMESERVER_1_IP: "192.168.2.1"

      NP_SPEEDTEST_ENABLED: "false"
      NP_SPEEDTEST_INTERVAL: "937"

      NP_REDIS_HOST: "netprobe-redis"
      NP_REDIS_PORT: "6379"
      NP_REDIS_DB: "0"
      NP_REDIS_PASSWORD: "password"

      NP_PRESENTATION_PORT: "5000"
      NP_PRESENTATION_INTERFACE: "0.0.0.0"
    ports:
      - "5000:5000"
    networks:
      - netprobe
    dns:
      - 8.8.8.8
      - 8.8.4.4
