{
 "title": "Internet Speed",
 "tags": [ "speedtest" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "speedtest_offset", "query": "90m" },
   { "name": "speedtest_download", "query": "800" },
   { "name": "speedtest_upload", "query": "800" }
  ]
 },
 "panels": [
  { "title": "QUICK VIEW", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NETWORK SCORE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "(\n(  1 - $WEIGHT_LOSS * $CV_LOSS)\n  - ($WEIGHT_JITTER * $CV_JITTER)\n  - ($WEIGHT_LATENCY * $CV_LATENCY)\n  - ($WEIGHT_INTERNAL_DNS_LATENCY * $CV_IDL)\n  - ($WEIGHT_EXTERNAL_DNS_LATENCY * $CV_EDL)\n  - ($WEIGHT_STU * $CV_STU)\n  - ($WEIGHT_STD * $CV_STD)\n)",
     "type": "math"
    }
   ]
  },
  {
   "title": "DOWNLOAD SPEED",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(speedtest_download_bytes[$speedtest_offset]) * 8",
     "legendFormat": "Average Download Speed"
    }
   ]
  },
  {
   "title": "JITTER",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netprobe_network_stats{type=\"jitter\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "INTERNAL AVG DNS LATENCY",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(netprobe_dns_stats{type=\"internal\"})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "INTERNAL DNS LATENCY",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(netprobe_dns_stats{type=\"internal\"})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "PACKET LOSS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(netprobe_network_stats{type=\"loss\"})",
     "legendFormat": "Packet Loss"
    }
   ]
  },
  {
   "title": "UPLOAD SPEED",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(speedtest_upload_bytes[$speedtest_offset]) * 8",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netprobe_network_stats{type=\"latency\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "EXTERNAL AVG DNS LATENCY",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(netprobe_dns_stats{type=\"external\"})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "EXTERNAL DNS LATENCY",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netprobe_dns_stats{type=\"external\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  { "title": "DETAILED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "NETWORK SCORE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expression": "(\n(  1 - $WEIGHT_LOSS * $CV_LOSS)\n  - ($WEIGHT_JITTER * $CV_JITTER)\n  - ($WEIGHT_LATENCY * $CV_LATENCY)\n  - ($WEIGHT_INTERNAL_DNS_LATENCY * $CV_IDL)\n  - ($WEIGHT_EXTERNAL_DNS_LATENCY * $CV_EDL)\n  - ($WEIGHT_STU * $CV_STU)\n  - ($WEIGHT_STD * $CV_STD)\n)",
     "type": "math"
    },
    { "expression": "1 - ($WEIGHT_STU * $CV_STU)", "type": "math" },
    { "expression": "1 - ($WEIGHT_STD * $CV_STD)", "type": "math" },
    {
     "expr": "netprobe_health_score{type=\"speedtest_overall\"}",
     "legendFormat": "SPEED TEST OVERALL"
    },
    {
     "expression": "1 - ($WEIGHT_EXTERNAL_DNS_LATENCY * $CV_EDL)",
     "type": "math"
    },
    {
     "expression": "1 - ($WEIGHT_INTERNAL_DNS_LATENCY * $CV_IDL)",
     "type": "math"
    },
    {
     "expression": "1 - ($WEIGHT_LATENCY * $CV_LATENCY)",
     "type": "math"
    },
    {
     "expression": "1 - ($WEIGHT_JITTER * $CV_JITTER)",
     "type": "math"
    },
    { "expression": "1 - ($WEIGHT_LOSS * $CV_LOSS)", "type": "math" }
   ]
  },
  {
   "title": "JITTER",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "speedtest_jittter_seconds", "legendFormat": "Speed Test Jitter" },
    {
     "expr": "netprobe_network_stats{type=\"jitter\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "speedtest_latency_seconds", "legendFormat": "Speed Test Latency" },
    {
     "expr": "netprobe_network_stats{type=\"latency\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "JITTER AVERAGE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "netprobe_network_stats{type=\"jitter\"}",
     "legendFormat": "np_jitter"
    },
    { "expr": "speedtest_jittter_seconds", "legendFormat": "st_jitter" }
   ]
  },
  {
   "title": "LATENCY AVERAGE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "netprobe_network_stats{type=\"latency\"}",
     "legendFormat": "{{target}}"
    },
    { "expr": "speedtest_latency_seconds", "legendFormat": "speedtest_latency_seconds" }
   ]
  },
  {
   "title": "DOWNSTREAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    { "expr": "speedtest_download_bytes*8", "legendFormat": "Download Speed" }
   ]
  },
  {
   "title": "UPSTREAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    { "expr": "speedtest_upload_bytes*8", "legendFormat": "Upload Speed" }
   ]
  },
  {
   "title": "DNS LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "netprobe_dns_stats{type=\"external\"}",
     "legendFormat": "{{server}}"
    },
    {
     "expr": "netprobe_dns_stats{type=~\"internal\"}",
     "legendFormat": "{{server}} ({{type}})"
    }
   ]
  },
  {
   "title": "DNS LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(netprobe_dns_stats{type=\"internal\"})",
     "legendFormat": "Internal"
    },
    {
     "expr": "avg(netprobe_dns_stats{type=\"external\"})",
     "legendFormat": "External"
    }
   ]
  },
  {
   "title": "PACKET LOSS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "netprobe_network_stats{type=\"loss\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "NETWORK RX/TX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "-(sum(rate(node_network_receive_bytes_total{instance=~\"(anaxes|mustafar|coruscant).bit13.local:1?9100\"}[$__rate_interval])*8))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=~\"(anaxes|mustafar|coruscant).bit13.local:1?9100\"}[$__rate_interval])*8)",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "CPU TEMP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "(node_thermal_zone_temp{instance=~\"(anaxes|mustafar|coruscant).bit13.local:19100\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SPEED TEST DURATION",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "scripts_duration_seconds{script=\"speedtest\", quantile=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}